name: 'Were only docs updated'
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
inputs:
  commit-range:
    description: 'commit range'
    required: true
outputs:
  were-only-docs-updated:
    description: "Were only docs updated"
    value: ${{ steps.were-only-docs-updated-id.outputs.were-only-docs-updated }}
runs:
  using: "composite"
  steps:
    - id: were-only-docs-updated-id
      shell: bash
      run: |
        echo "commit range: ${{ inputs.commit-range }}"
        git diff --name-only ${{ inputs.commit-range }} | grep -qvE '(\.md$)|(^(docs|g11n-ws/docs))/' || {
          echo "::set-output name=were-only-docs-updated::yes"
          echo "were-only-docs-updated: yes."
          exit
        }
        echo "::set-output name=were-only-docs-updated::no"
        echo "were-only-docs-updated: no."
